name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12h
  workflow_dispatch:
  push:
    branches:
      - main  # ou 'master', se for o caso

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        with:
          github_user_name: romulo581
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
